# Generated by Django 5.2.7 on 2025-10-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0003_alter_job_status_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, help_text='Razorpay order ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, help_text='Razorpay payment ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_signature',
            field=models.CharField(blank=True, help_text='Razorpay signature for verification', max_length=500, null=True),
        ),
    ]
