# Generated by Django 5.2.7 on 2025-10-15 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0004_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
