# Generated by Django 5.2.7 on 2025-10-15 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_auth', '0005_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('payment_method', models.CharField(blank=True, help_text='e.g. credit_card, paypal, stripe, wallet', max_length=50, null=True)),
                ('status', models.CharField(default='pending', help_text='pending | completed | failed | refunded', max_length=50)),
                ('transaction_id', models.CharField(blank=True, help_text='External reference from payment gateway', max_length=255, null=True, unique=True)),
                ('razorpay_order_id', models.CharField(blank=True, help_text='Razorpay order ID', max_length=255, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, help_text='Razorpay payment ID', max_length=255, null=True)),
                ('razorpay_signature', models.CharField(blank=True, help_text='Razorpay signature for verification', max_length=500, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api_auth.client')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api_auth.freelancer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api_auth.job')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
